version: '3'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: zer0pts
      MYSQL_USER: zer0ptsuser
      MYSQL_PASSWORD: zer0ptspassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - 13306:3306

    command: mysqld --general-log=1 --general-log-file=/var/lib/mysql/general-query.log

  adminer:
    image: adminer
    ports:
      - 9000:8080

  redis:
    image: redis:5
    ports:
      - 6379:6379

  transfersh:
    image: dutchcoders/transfer.sh
    ports:
      - 9999:8080

    command: '--http-auth-user transfer --http-auth-pass password --provider local --basedir /tmp/'
