CREATE TABLE IF NOT EXISTS teams (
    id INT UNSIGNED NOT NULL,
    teamname VARCHAR(64) NOT NULL,
    token VARCHAR(64) NOT NULL,
    country_code CHAR(3) NOT NULL,
    is_hidden BOOLEAN NOT NULL DEFAULT FALSE,

    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY(`id`),
    UNIQUE KEY(`teamname`),
    UNIQUE KEY(`token`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS users (
    id INT UNSIGNED NOT NULL,
    username VARCHAR(64) NOT NULL,
    email VARCHAR(128) NOT NULL,
    password_hash VARCHAR(64) NOT NULL,
    icon_path TEXT,
    team_id INT UNSIGNED NOT NULL,
    is_hidden BOOLEAN NOT NULL DEFAULT FALSE,
    is_admin BOOLEAN NOT NULL DEFAULT FALSE,

    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY(`id`),
    UNIQUE KEY(`username`),
    UNIQUE KEY(`email`),
    FOREIGN KEY(`team_id`) REFERENCES `teams`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tokens (
    user_id INT UNSIGNED NOT NULL,
    token VARCHAR(64) NOT NULL,
    expires_at INT UNSIGNED NOT NULL,
    revoked BOOLEAN NOT NULL DEFAULT FALSE,

    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (`token`),
    FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS password_reset_tokens (
    user_id INT UNSIGNED NOT NULL,
    token VARCHAR(64) NOT NULL,
    expires_at INT UNSIGNED NOT NULL,
    revoked BOOLEAN NOT NULL DEFAULT FALSE,

    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (`token`),
    FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS challenges (
    id INT UNSIGNED NOT NULL,
    name VARCHAR(64) NOT NULL,
    flag VARCHAR(256) NOT NULL,
    description TEXT NOT NULL,
    category TEXT NOT NULL,
    difficulty TEXT NOT NULL,
    author TEXT NOT NULL,
    base_score INT UNSIGNED NOT NULL,
    is_open BOOLEAN NOT NULL DEFAULT FALSE,
    is_dynamic BOOLEAN NOT NULL DEFAULT TRUE,
    is_questionary BOOLEAN NOT NULL DEFAULT FALSE,
    host TEXT,
    port TEXT,

    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY(`id`),
    UNIQUE KEY (`name`),
    UNIQUE KEY (`flag`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS challenge_tags (
    id INT UNSIGNED NOT NULL,
    challenge_id INT UNSIGNED NOT NULL,
    tag VARCHAR(256) NOT NULL,

    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY(`id`),
    UNIQUE `chal_tag` (`challenge_id`, `tag`),
    FOREIGN KEY(`challenge_id`) REFERENCES `challenges`(`id`) ON DELETE CASCADE ON UPDATE CASCADE

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS challenge_attachments (
    id INT UNSIGNED NOT NULL,
    challenge_id INT UNSIGNED NOT NULL,
    url VARCHAR(512) NOT NULL,

    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY(`id`),
    UNIQUE `chal_url` (`challenge_id`, `url`),
    FOREIGN KEY(`challenge_id`) REFERENCES `challenges`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS submissions (
    id INT UNSIGNED NOT NULL,
    challenge_id INT UNSIGNED, -- may be null on delete
    user_id INT UNSIGNED,
    team_id INT UNSIGNED,
    flag TEXT NOT NULL,

    submitted_at INT UNSIGNED NOT NULL,
    is_correct BOOLEAN NOT NULL,
    is_valid BOOLEAN NOT NULL,

    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY(`id`),
    FOREIGN KEY(`challenge_id`) REFERENCES `challenges`(`id`) ON DELETE SET NULL ON UPDATE SET NULL,
    FOREIGN KEY(`user_id`) REFERENCES `users`(`id`) ON DELETE SET NULL ON UPDATE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS config (
    ctf_name VARCHAR(32) NOT NULL,
    start_at DATETIME NOT NULL,
    end_at DATETIME NOT NULL,

    min_score INT NOT NULL,
    easy_solves INT NOT NULL,
    medium_solves INT NOT NULL,

    lock_second INT NOT NULL,
    lock_duration INT NOT NULL,
    lock_count INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
